# Generated by Django 3.2.5 on 2021-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeuBlog', '0009_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click no link acima para ler o conteudo', max_length=255),
        ),
    ]
